### ISSUE TITLE
No HTML files

### ISSUE THREAD

**Issue by jaworskm** [miickel/gulp-angular-templatecache#100] opened 2015-08-24 19:20 UTC
If a use gulp.src('src/**/*.html')... with this tool and there are no html files, the tool breaks. Could you upgrade to gracefully handle the case when no files are passed to the tool.

Thanks!

**Comment by remento** [comment] 2015-08-24 22:08
The issue is with using gulp-header 1.5, see https://github.com/tracker1/gulp-header/issues/21

You can get gulp-angular-templatecache to use an older version by:

    npm cache clean
    npm uninstall gulp-angular-templatecache
    npm install gulp-header@1.2.2 --save-dev
    npm install gulp-angular-templatecache --save-dev

To see what version of gulp header you are using…

    npm list gulp-header

Note that the version of gulp-header to avoid is version 1.5

**Comment by tracker1** [comment] 2015-08-25 01:51
This should be fixed in gulp-header `1.5.2`

**Comment by miickel** [comment] 2015-08-25 07:13
duplicate of #97

**Closed** 2015-08-26 17:19 UTC
